events {
    worker_connections 1024;
}

http {
    
    upstream backend_anaiperez {
        server 192.168.10.2:80;
        server 192.168.10.3:80;
        server 192.168.10.4:80;
        server 192.168.10.5:80;
        server 192.168.10.6:80;
        server 192.168.10.7:80;
        server 192.168.10.8:80;
        server 192.168.10.9:80;
    }

    server {
        

        listen 443 ssl http2;
        server_name localhost;

        
        ssl_certificate     /etc/nginx/ssl/certificado_anaiperez_bundle.crt;
        ssl_certificate_key /etc/nginx/ssl/certificado_anaiperez.key;

# --- TAREA A2-A4 ---
        ssl_protocols  TLSv1.2 TLSv1.3;  
        ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256';
        ssl_prefer_server_ciphers on;

# --- TAREA A3 ---
        ssl_session_cache shared:SSL:10m;  
        ssl_session_timeout 1h;           
        ssl_session_tickets on;           


        location / {
            proxy_pass http://backend_anaiperez;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Cookie $http_cookie;
            proxy_hide_header Set-Cookie; 
        }
    }

    #redirigir tráfico HTTP 80 a HTTPS 443
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }
}
